Added failling test
rectorphp/rector-phpunit pull request #168
Opened 2023-04-15 13:40 UTC by staabm

closes https://github.com/rectorphp/rector/issues/7873

2023-04-15 14:17 UTC, OskarStark approved these changes

2023-04-15 14:18 UTC, OskarStark commented
This looks good to me 👍🏻

2023-04-16 07:24 UTC, samsonasik commented on src/Rector/Class_/CoversAnnotationWithValueToAttributeRector.php
> +    private function resolveCoversClassAttributeGroups(Node\Stmt $node): array
```suggestion
    private function resolveCoversClassAttributeGroups(Class_|ClassMethod $node): array
```

2023-04-16 07:25 UTC, samsonasik commented on src/Rector/Class_/CoversAnnotationWithValueToAttributeRector.php
> +    private function resolveCoversFunctionAttributeGroups(Node\Stmt $node): array
```suggestion
    private function resolveCoversFunctionAttributeGroups(Class_|ClassMethod $node): array
```

2023-04-16 07:30 UTC, samsonasik approved these changes

2023-04-16 07:39 UTC, samsonasik requested changes
`resolveCoversClassAttributeGroups()` and `resolveCoversFunctionAttributeGroups()` has equal content, so one of them can be removed, as already cover both `Class_` and `ClassMethod`

2023-04-16 08:01 UTC, samsonasik approved these changes

2023-04-16 08:04 UTC, samsonasik commented
Thank you @staabm

2023-04-16 08:04 UTC, merged